[package]
authors = ["Steven Roose <steven@stevenroose.org>"]
edition = "2018"
name = "integration_test"
version = "0.1.0"

[dependencies]
bitcoin = {git = "https://github.com/oraichain/rust-dogecoin", rev = "ce0554a"}
bitcoincore-rpc = {path = "../client"}
lazy_static = "1.4.0"
log = "0.4"
